import type { Category, Leader, Market, UserPrediction } from './types';

export const USER = {
  username: 'HK_Forecaster',
  avatarEmoji: '🇭🇰',
  initialPoints: 1250,
  rank: 14,
  accuracy: 78,
};

export const CATEGORIES: Category[] = [
  { id: 'all', label: 'All', emoji: '🔥' },
  { id: 'weather', label: 'Weather', emoji: '🌧️' },
  { id: 'transit', label: 'Transit', emoji: '🚇' },
  { id: 'economy', label: 'Economy', emoji: '🏢' },
  { id: 'local', label: 'Local Life', emoji: '🍔' },
];

export const MARKETS: Market[] = [
  {
    id: 'typhoon-t8',
    category: 'weather',
    title: 'Will HKO issue a T8 Typhoon Signal before August 15, 2026?',
    endsIn: '15 days',
    participants: 1420,
    ptsStaked: 45200,
    yesPct: 68,
    yesOdds: 1.4,
    noOdds: 2.8,
    featured: true,
  },
  {
    id: 'ccl-140',
    category: 'economy',
    title: 'Will Centa-City Leading Index (CCL) hit 140 this quarter?',
    endsIn: '42 days',
    participants: 890,
    ptsStaked: 28400,
    yesPct: 41,
    yesOdds: 2.3,
    noOdds: 1.6,
  },
  {
    id: 'kwu-tung',
    category: 'transit',
    title: 'Will MTR Kwu Tung Station civil construction meet 2027 targets?',
    endsIn: '90 days',
    participants: 654,
    ptsStaked: 19800,
    yesPct: 82,
    yesOdds: 1.2,
    noOdds: 4.1,
  },
  {
    id: 'tourism-4m',
    category: 'economy',
    title: 'Will HK Tourism Board report over 4M arrivals this month?',
    endsIn: '12 days',
    participants: 1120,
    ptsStaked: 33100,
    yesPct: 64,
    yesOdds: 1.5,
    noOdds: 2.5,
  },
  {
    id: 'causeway-flagship',
    category: 'local',
    title:
      'Will a major overseas retail chain announce a Causeway Bay flagship next month?',
    endsIn: '28 days',
    participants: 732,
    ptsStaked: 15600,
    yesPct: 51,
    yesOdds: 1.9,
    noOdds: 1.9,
  },
  {
    id: 'rainstorm-black',
    category: 'weather',
    title: 'Will HKO issue a Black Rainstorm Warning this week?',
    endsIn: '4 days',
    participants: 2104,
    ptsStaked: 52300,
    yesPct: 37,
    yesOdds: 2.5,
    noOdds: 1.5,
  },
  {
    id: 'ferry-delay',
    category: 'transit',
    title: 'Will Star Ferry report >10% delay rate this weekend?',
    endsIn: '3 days',
    participants: 418,
    ptsStaked: 9200,
    yesPct: 29,
    yesOdds: 3.1,
    noOdds: 1.4,
  },
];

export const LEADERS: Leader[] = [
  {
    id: '1',
    username: 'HK_Weather_Guru',
    accuracy: 89,
    badge: 'HKO Prophet',
    points: 18420,
    avatarEmoji: '🌀',
  },
  {
    id: '2',
    username: 'MTR_Insider',
    accuracy: 84,
    badge: 'Transit Specialist',
    points: 15210,
    avatarEmoji: '🚆',
  },
  {
    id: '3',
    username: 'Property_Whiz',
    accuracy: 81,
    badge: 'Property Hawk',
    points: 14100,
    avatarEmoji: '🏙️',
  },
  {
    id: '4',
    username: 'Causeway_Pulse',
    accuracy: 80,
    badge: 'Local Life Ace',
    points: 12880,
    avatarEmoji: '🛍️',
  },
  {
    id: '5',
    username: 'Harbour_Stats',
    accuracy: 79,
    badge: 'Economy Scout',
    points: 11950,
    avatarEmoji: '📊',
  },
  {
    id: '6',
    username: 'Typhoon_Tracker',
    accuracy: 79,
    badge: 'HKO Prophet',
    points: 10840,
    avatarEmoji: '💨',
  },
  {
    id: '7',
    username: 'DimSum_Data',
    accuracy: 78,
    badge: 'Local Life Ace',
    points: 9920,
    avatarEmoji: '🥟',
  },
  {
    id: '14',
    username: 'HK_Forecaster',
    accuracy: 78,
    badge: 'Rising Predictor',
    points: 1250,
    avatarEmoji: '🇭🇰',
  },
];

/** Seed portfolio — active stakes are already committed; wallet still starts at 1,250. */
export const INITIAL_USER_PREDICTIONS: UserPrediction[] = [
  {
    id: 'pred-active-1',
    marketId: 'tourism-4m',
    marketTitle:
      'Will HK Tourism Board report over 4M arrivals this month?',
    predictionType: 'YES',
    stakedAmount: 150,
    potentialPayout: 225,
    odds: 1.5,
    timestamp: Date.now() - 1000 * 60 * 60 * 26,
    status: 'ACTIVE',
    endsIn: '12 days',
  },
  {
    id: 'pred-active-2',
    marketId: 'kwu-tung',
    marketTitle:
      'Will MTR Kwu Tung Station civil construction meet 2027 targets?',
    predictionType: 'YES',
    stakedAmount: 200,
    potentialPayout: 240,
    odds: 1.2,
    timestamp: Date.now() - 1000 * 60 * 60 * 8,
    status: 'ACTIVE',
    endsIn: '90 days',
  },
  {
    id: 'pred-hist-1',
    marketId: 'hist-t1',
    marketTitle: 'Will HKO issue a T3 Signal during last weekend?',
    predictionType: 'YES',
    stakedAmount: 200,
    potentialPayout: 320,
    odds: 1.6,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 9,
    status: 'SETTLED',
    result: 'WIN',
    settledPnl: 280,
  },
  {
    id: 'pred-hist-2',
    marketId: 'hist-ferry',
    marketTitle: 'Will Star Ferry cancel evening sailings last Friday?',
    predictionType: 'NO',
    stakedAmount: 100,
    potentialPayout: 150,
    odds: 1.5,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 12,
    status: 'SETTLED',
    result: 'LOSS',
    settledPnl: -100,
  },
  {
    id: 'pred-hist-3',
    marketId: 'hist-retail',
    marketTitle: 'Will a new flagship open in Mong Kok this quarter?',
    predictionType: 'YES',
    stakedAmount: 120,
    potentialPayout: 240,
    odds: 2.0,
    timestamp: Date.now() - 1000 * 60 * 60 * 24 * 18,
    status: 'SETTLED',
    result: 'WIN',
    settledPnl: 120,
  },
];

export const formatPts = (n: number) => n.toLocaleString('en-HK');

export function getActiveStakeForMarket(
  predictions: UserPrediction[],
  marketId: string,
): UserPrediction | undefined {
  return predictions.find(
    (p) => p.marketId === marketId && p.status === 'ACTIVE',
  );
}
